services:
  app.admin.event:
    class: App\Admin\EventAdmin
    arguments: [~, App\Entity\Event, App\Admin\Controller\EventAdminController]
    tags:
      - { name: sonata.admin, manager_type: orm, audit: false, group: Мероприятия, label: Список мероприятий }

  app.admin.classification.tag:
    class: App\Admin\Classification\TagAdmin
    arguments: [~, App\Entity\Classification\Tag, SonataAdminBundle:CRUD]
    tags:
      - { name: sonata.admin, manager_type: orm, audit: false, group: Мероприятия, label: Теги мероприятий }

  app.admin.event_slider:
    class: App\Admin\EventSliderAdmin
    arguments: [~, App\Entity\EventSlider, SonataAdminBundle:CRUD]
    tags:
      - { name: sonata.admin, manager_type: orm, audit: false, group: Мероприятия, label: Слайдер "Мероприятия" }

  app.admin.news:
    class: App\Admin\NewsAdmin
    arguments: [~, App\Entity\News, SonataAdminBundle:CRUD]
    tags:
      - { name: sonata.admin, manager_type: orm, audit: false, group: Новости, label: Новости }

  app.admin.page:
    class: App\Admin\PageAdmin
    arguments: [~, App\Entity\Page, SonataAdminBundle:CRUD]
    tags:
      - { name: sonata.admin, manager_type: orm, audit: false, group: Статичные страницы, label: Страницы }

  app.admin.page_slides:
    class: App\Admin\PageSlidesAdmin
    arguments: [~, App\Entity\PageSlides, SonataAdminBundle:CRUD]
    tags:
      - { name: sonata.admin, manager_type: orm, audit: false, group: Статичные страницы, label: Слайды }

  app.admin.menu:
    class: App\Admin\MenuAdmin
    arguments: [~, App\Entity\Menu, SonataAdminBundle:CRUD]
    tags:
      - { name: sonata.admin, manager_type: orm, audit: false, group: Сайт, label: Меню сайта }

  app.admin.subscribe:
    class: App\Admin\SubscribeAdmin
    arguments: [~, App\Entity\Subscribe, SonataAdminBundle:CRUD]
    tags:
      - { name: sonata.admin, manager_type: orm, audit: false, group: Сайт, label: Подписки }