services:
  app.admin.handbook.city_admin:
      class: App\Admin\Handbook\CityAdmin
      arguments: [~, App\Entity\Handbook\City, SonataAdminBundle:CRUD]
      tags:
          - { name: sonata.admin, manager_type: orm, audit: false, group: Справочники, label: Города }
