address: 'Новосибирск, ул. Октябрьская 42 офис 513'
phone: +7(905)2814286
email: seeekji@gmail.com
vk: test
facebook: test
instagram: null
city_count: 1
hall_count: null
event_count: null
email_send_from: test@test.com
email_send_to: test@test.com
