address: 'Новосибирск, ул. Октябрьская 42 офис 513'
phone: +79999999999
email: test@test.com
vk: test
facebook: test
instagram: null
city_count: 1
hall_count: null
event_count: null
email_send_from: test@test.com
email_send_to: test@test.com
